# Generated by Django 2.1.5 on 2019-01-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_readnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='read_count',
            new_name='read_num',
        ),
    ]
