# Generated by Django 2.1.5 on 2019-01-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20190130_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='read_num',
        ),
    ]
