# Generated by Django 2.1.5 on 2019-01-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_remove_blog_read_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
