# Generated by Django 2.1.5 on 2019-05-23 00:06

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20190214_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='avator',
            field=imagekit.models.fields.ProcessedImageField(default='media/avator/default.jpg', upload_to='media/avator'),
        ),
    ]
