# Generated by Django 2.1.5 on 2019-05-23 00:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_blog_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='avator',
            field=imagekit.models.fields.ProcessedImageField(default='/avator/default.jpg', upload_to='media/avator'),
        ),
    ]
