# Generated by Django 2.1.5 on 2019-05-23 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_auto_20190523_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='avator',
        ),
    ]
