# Generated by Django 2.1.5 on 2019-05-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(max_length=20, verbose_name='昵称'),
        ),
    ]
