# Generated by Django 2.1.5 on 2019-02-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20190204_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parrent_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='parrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comment.Comment'),
        ),
    ]
